export default function Head() {
  return (
    <>
      <title>DUBISDEV: Web & Desktop Development</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="author" content="David Jiménez" />
      <link rel="canonical" href="https://dubis.dev" />
      <link
        rel="shortcut icon"
        href="https://avatars.githubusercontent.com/u/77246331"
        type="image/x-icon"
      />
    </>
  );
}
